# Generated by Django 6.0 on 2025-12-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="tax_uploads/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("URA", "URA Tax Payments"),
                            ("LGRB", "LGRB Submissions"),
                        ],
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.PositiveIntegerField()),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("records_imported", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LGRBSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_row_number",
                    models.PositiveIntegerField(
                        help_text="Row number in original Excel file"
                    ),
                ),
                (
                    "operator_category",
                    models.CharField(
                        choices=[
                            ("GENERAL BETTING", "General Betting"),
                            ("CASINOS", "Casinos"),
                            ("SPORTS BETTING", "Sports Betting"),
                            ("LOTTERY", "Lottery"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("operator_name", models.CharField(max_length=255)),
                (
                    "operator_tin",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("submission_date", models.DateField()),
                ("quarter", models.CharField(max_length=10)),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_payouts", models.DecimalField(decimal_places=2, max_digits=15)),
                ("win_loss", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "withholding_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("gaming_tax", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_expected_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "standardized_operator_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lgrb_submissions",
                        to="dashboard.excelupload",
                    ),
                ),
            ],
            options={
                "ordering": ["submission_date", "operator_name"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWHTVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_year",
                    models.DateField(db_index=True, help_text="First day of the month"),
                ),
                ("operator_name", models.CharField(max_length=255)),
                (
                    "standardized_operator_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "lgrb_withholding_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("lgrb_submission_count", models.PositiveIntegerField()),
                (
                    "ura_withholding_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("ura_payment_count", models.PositiveIntegerField()),
                (
                    "absolute_variance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "percentage_variance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("is_possible_late_payment", models.BooleanField(default=False)),
                ("is_early_payment", models.BooleanField(default=False)),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("analysis_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-month_year", "operator_name"],
                "indexes": [
                    models.Index(
                        fields=["month_year", "standardized_operator_name"],
                        name="dashboard_m_month_y_91afe9_idx",
                    )
                ],
                "unique_together": {("month_year", "standardized_operator_name")},
            },
        ),
        migrations.CreateModel(
            name="URAPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_row_number",
                    models.PositiveIntegerField(
                        help_text="Row number in original Excel file"
                    ),
                ),
                ("tin", models.CharField(db_index=True, max_length=50)),
                ("taxpayer_name", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=100)),
                ("prn", models.CharField(max_length=50)),
                ("bank", models.CharField(max_length=100)),
                ("taxpayer_type", models.CharField(max_length=50)),
                (
                    "tax_head",
                    models.CharField(
                        choices=[
                            ("Gaming Tax", "Gaming Tax"),
                            ("Withholding Tax", "Withholding Tax"),
                            ("PAYE", "PAYE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location_name", models.CharField(max_length=100)),
                ("bank_realization_date", models.DateField(db_index=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("ELECTRONIC", "Electronic Transfer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "standardized_taxpayer_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ura_payments",
                        to="dashboard.excelupload",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_realization_date", "taxpayer_name"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyGamingTaxVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wednesday_date",
                    models.DateField(
                        db_index=True, help_text="Wednesday ending the period"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Previous Wednesday + 1 day"),
                ),
                ("period_end", models.DateField(help_text="Current Wednesday")),
                ("operator_name", models.CharField(max_length=255)),
                (
                    "standardized_operator_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "lgrb_gaming_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "lgrb_submission_count",
                    models.PositiveIntegerField(
                        help_text="Number of LGRB submissions aggregated"
                    ),
                ),
                (
                    "ura_gaming_tax",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "ura_payment_count",
                    models.PositiveIntegerField(
                        help_text="Number of URA payments aggregated"
                    ),
                ),
                (
                    "absolute_variance",
                    models.DecimalField(
                        decimal_places=2, help_text="URA - LGRB", max_digits=15
                    ),
                ),
                (
                    "percentage_variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="(URA - LGRB) / LGRB * 100",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_possible_late_payment",
                    models.BooleanField(
                        default=False, help_text="LGRB = 0 but URA > 0"
                    ),
                ),
                (
                    "is_early_payment",
                    models.BooleanField(
                        default=False, help_text="URA = 0 but LGRB > 0"
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("analysis_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-wednesday_date", "operator_name"],
                "indexes": [
                    models.Index(
                        fields=["wednesday_date", "standardized_operator_name"],
                        name="dashboard_w_wednesd_d64cb3_idx",
                    ),
                    models.Index(
                        fields=["is_possible_late_payment"],
                        name="dashboard_w_is_poss_243f71_idx",
                    ),
                    models.Index(
                        fields=["is_early_payment"],
                        name="dashboard_w_is_earl_601a50_idx",
                    ),
                ],
                "unique_together": {("wednesday_date", "standardized_operator_name")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="dashboard_a_user_id_96898d_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="dashboard_a_action_81911a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="excelupload",
            index=models.Index(
                fields=["file_type", "-uploaded_at"],
                name="dashboard_e_file_ty_913c86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lgrbsubmission",
            index=models.Index(
                fields=["submission_date", "standardized_operator_name"],
                name="dashboard_l_submiss_fcb6b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lgrbsubmission",
            index=models.Index(
                fields=["standardized_operator_name"],
                name="dashboard_l_standar_fc1788_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lgrbsubmission",
            index=models.Index(
                fields=["submission_date"], name="dashboard_l_submiss_50b13c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urapayment",
            index=models.Index(
                fields=["bank_realization_date", "standardized_taxpayer_name"],
                name="dashboard_u_bank_re_3bc980_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="urapayment",
            index=models.Index(
                fields=["standardized_taxpayer_name"],
                name="dashboard_u_standar_f80836_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="urapayment",
            index=models.Index(
                fields=["tax_head", "bank_realization_date"],
                name="dashboard_u_tax_hea_dc5165_idx",
            ),
        ),
    ]
