# Generated by Django 6.0 on 2025-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lgrbsubmission",
            name="operator_category",
            field=models.CharField(
                choices=[
                    ("GENERAL BETTING", "General Betting"),
                    ("CASINOS", "Casinos"),
                    ("SLOT MACHINES", "Slot Machines"),
                    ("BINGO", "Bingo"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
